### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by fyhhub** [pumelotea/happyboot-tiger#31]
![car1](https://user-images.githubusercontent.com/38740836/203886003-020ccb9a-7406-481e-b7ee-ee1868b6d39d.gif)

**Comment by fyhhub** [comment]
这里会疯狂闪动

**Comment by pumelotea** [comment]
浏览器类型、浏览器版本号，发一下

**Comment by pumelotea** [comment]
浏览器类型、浏览器版本号，发一下

**Comment by pumelotea** [comment]
ui库在宽度比较小的情况导致了换行触发的
